# Generated by Django 2.2 on 2019-04-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20190424_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationcomment',
            old_name='user',
            new_name='username',
        ),
    ]
