# Generated by Django 2.2.1 on 2019-05-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20190430_1220'),
        ('translation', '0003_translation_likes'),
    ]

    operations = [
    ]
