# Generated by Django 2.2.1 on 2019-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_merge_20190507_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
