# Generated by Django 2.2.1 on 2019-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_auto_20190507_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='translationcomment',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='translation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
