# Generated by Django 2.2.1 on 2019-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_merge_20190503_1847'),
        ('translation', '0006_auto_20190509_1651'),
    ]

    operations = [
    ]
