# Generated by Django 2.2.1 on 2019-05-10 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0007_merge_20190510_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='phrase_author',
        ),
        migrations.AddField(
            model_name='phrase',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
