# Generated by Django 2.2.1 on 2019-05-10 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20190510_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrase_usernames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_usernames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translationcomment',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
